version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/aivero-rgbd-toolkit"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/gst-colorizer"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/gst-depth-meta-rs"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/gst-frame-aligner"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/gst-k4a"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/gst-realsense"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/gst-rgbd"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/libk4a-rs"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/libk4a-rs-sys"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/rgbd-enums"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "cargo"
    directory: "/rgbd-timestamps"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"