variables:
  CONAN_SKIP_BROKEN_SYMLINKS_CHECK: True

include:
  - project: 'aivero/cloud/cicd'
    file: 'conan-ci-base.yml'
  - project: 'aivero/cloud/cicd'
    file: 'conan-ci-arm64v8.yml'
  - local: '.gitlab-ci-tx1.yml'
