stages:
  - build
  - test
generate-config:
  image: aivero/conan:focal-x86_64
  tags: [x86_64,aws]
  stage: build
  rules:
    - if: '$PACKAGE_MANAGER_SET == null && $CI_PIPELINE_SOURCE != "merge_request_event"'
  variables:
    CICD_BRANCH: stable
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --prune --depth 50
  script:
    - python3 scripts/create_aliases.py
    - deno run --unstable --allow-all --import-map https://gitlab.com/aivero/open-source/cicd/-/raw/$CICD_BRANCH/import_map.json https://gitlab.com/aivero/open-source/cicd/-/raw/$CICD_BRANCH/lib/es6/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml
      - build_order.json
      - lock.bundle
      - "*.lock"

child-pipeline:
  stage: test
  rules:
    - if: '$PACKAGE_MANAGER_SET == null && $CI_PIPELINE_SOURCE != "merge_request_event"'
  trigger:
    strategy: depend
    include:
      - artifact: generated-config.yml
        job: generate-config

include: '/.gitlab/dependabot-gitlab-ci.yml'
