# #######
# Build and test the Release version:
# #######

armv8-bionic-release-stable:
  extends:
    - .core
    - .armv8
    - .release
    - .stable
  variables:
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"

armv8-bionic-release-testing:
  extends:
    - .core
    - .armv8
    - .release
    - .testing
  variables:
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"

armv8-bionic-release-stable-package:
  extends:
    - .armv8
    - .release
    - .stable
    - .package
  variables:
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"


armv8-bionic-testing-tx1:
  extends: armv8-bionic-release-testing
  variables:
    CONAN_BUILD_OPTIONS: "-o jetson=Nano"
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"

armv8-bionic-release-tx1:
  extends: armv8-bionic-release-stable
  variables:
    CONAN_BUILD_OPTIONS: "-o jetson=Nano"
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"
