include:
  - project: 'aivero/cloud/cicd'
    file: 'conan-ci-base.yml'

# #######
# Build and test the Release version:
# #######

deploy_tarball_x86:
  stage: build
  variables:
    CONAN_BUILD_TYPE: Release
    CONAN_IMAGE_ARCH: amd64
    CONAN_ARCH: x86_64
  tags:
    - x86_64
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"; fi # Not all packages use GIT_TAG and GIT_BRANCH yet
    - if [ -n "$APT_INSTALL" ]; then apt update && apt install --no-install-recommends -y $APT_INSTALL; fi
    - if [ -n "$APT_REMOVE" ]; then apt update && apt remove -y $APT_REMOVE; fi
    - conan create . aivero/stable --update
    - conan install aivero_rgbd_toolkit/$CI_COMMIT_REF_SLUG@aivero/stable -if /opt/aivero/rgbd_toolkit_$CONAN_ARCH
    - tar cvfj aivero_rgbd_toolkit_$CI_COMMIT_REF_SLUG_$CONAN_ARCH.tar.bz2 /opt/aivero/rgbd_toolkit_$CONAN_ARCH
  artifacts:
    expire_in: 1 month
    paths:
      - aivero_rgbd_toolkit*.tar.bz2
    when: always

deploy_tarball_arvm8:
  stage: build
  variables:
    CONAN_BUILD_TYPE: Release
    CONAN_IMAGE_ARCH: arm64
    CONAN_ARCH: armv8
  tags:
    - armv8
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"; fi # Not all packages use GIT_TAG and GIT_BRANCH yet
    - if [ -n "$APT_INSTALL" ]; then apt update && apt install --no-install-recommends -y $APT_INSTALL; fi
    - if [ -n "$APT_REMOVE" ]; then apt update && apt remove -y $APT_REMOVE; fi
    - conan create . aivero/stable --update
    - conan install aivero_rgbd_toolkit/$CI_COMMIT_REF_SLUG@aivero/stable -if /opt/aivero/rgbd_toolkit_$CONAN_ARCH
    - tar cvfj aivero_rgbd_toolkit_$CI_COMMIT_REF_SLUG_$CONAN_ARCH.tar.bz2 /opt/aivero/rgbd_toolkit_$CONAN_ARCH
  artifacts:
    expire_in: 1 month
    paths:
      - aivero_rgbd_toolkit*.tar.bz2
    when: always
