armv8-bionic-debug-tx1:
  extends: armv8-bionic-debug-stable
  variables:
    CONAN_BUILD_OPTIONS: "-o jetson=Nano"

armv8-bionic-release-tx1:
  extends: armv8-bionic-release-stable
  variables:
    CONAN_BUILD_OPTIONS: "-o jetson=Nano"