stages:
  - build
  - test
generate-config:
  image: registry.gitlab.com/aivero/open-source/contrib/focal-deno/linux-x86_64:master
  tags: [saas-linux-large-amd64]
  stage: build
  rules:
    - if: '$PACKAGE_MANAGER_SET == null && $CI_PIPELINE_SOURCE != "merge_request_event" && $TRIAGE_BOT_SCHEDULED == null'
  variables:
    CICD_BRANCH: stable
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --prune --depth 50
    XDG_CACHE_HOME: $CI_PROJECT_DIR
  script:
    - python3 scripts/create_aliases.py
    - deno run --unstable --allow-all --import-map https://gitlab.com/aivero/open-source/cicd/-/raw/$CICD_BRANCH/import_map.json https://gitlab.com/aivero/open-source/cicd/-/raw/$CICD_BRANCH/lib/es6/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml

child-pipeline:
  stage: test
  rules:
    - if: '$PACKAGE_MANAGER_SET == null && $CI_PIPELINE_SOURCE != "merge_request_event" && $TRIAGE_BOT_SCHEDULED == null'
  trigger:
    strategy: depend
    include:
      - artifact: generated-config.yml
        job: generate-config

include: '/.gitlab/dependabot-gitlab-ci.yml'

dry-run:triage:
  image: ruby
  stage: build
  script:
    - gem install gitlab-triage
    - gitlab-triage --help
    - gitlab-triage --dry-run --token $API_TOKEN --source groups --source-id aivero/open-source
  rules:
    - if: '$TRIAGE_BOT_SCHEDULED != null && $CI_PIPELINE_SOURCE != "schedule"'
      when: manual

policy:run:
  image: ruby
  stage: build
  script:
    - gem install gitlab-triage
    - gitlab-triage --token $API_TOKEN --source groups --source-id aivero/open-source
  rules:
    - if: '$TRIAGE_BOT_SCHEDULED != null && $CI_PIPELINE_SOURCE != "schedule"'
      when: manual

schedule:policyrun:
  image: ruby
  stage: build
  script:
    - gem install gitlab-triage
    - gitlab-triage --token $API_TOKEN --source groups --source-id aivero/open-source
  only:
    - schedules
