stages:
  - build
  - test
generate-config:
  image: aivero/conan:focal-x86_64
  tags: [x86_64,aws]
  stage: build
  variables:
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --prune --depth 50
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - python3 scripts/create_aliases.py
    - deno run --unstable --allow-all --import-map https://gitlab.com/aivero/open-source/cicd/-/raw/stable/import_map.json https://gitlab.com/aivero/open-source/cicd/-/raw/stable/lib/es6_global/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml
      - build_order.json
      - lock.bundle
      - "*.lock"

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config
