stages:
  - init
  - build
  - test
alias-creator:
  image: aivero/conan:focal-x86_64
  tags: [x86_64]
  stage: init
  script:
    - python3 scripts/upload_aliases.py
  except:
    changes:
      - "*"
generate-config:
  image: aivero/conan:focal-x86_64
  tags: [x86_64]
  stage: build
  script:
    - deno run --unstable --allow-all --import-map https://gitlab.com/aivero/cicd/-/raw/master/import_map.json https://gitlab.com/aivero/cicd/-/raw/master/lib/es6_global/src/GenerateConfig.js
  variables:
    mode: git
  artifacts:
    paths:
      - generated-config.yml
      - build_order.json
      - lock.bundle

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config
