stages:
  - build
  - test

generate-config:
  image: aivero/conan:bionic-x86_64-dispatch
  stage: build
  script:
    - deno run --unstable --allow-all --import-map https://gitlab.com/aivero/cicd/-/raw/master/import_map.json https://gitlab.com/aivero/cicd/-/raw/master/lib/es6_global/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml
      - build_order.json
      - lock.bundle

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config
