stages:
  - init
  - build
  - test
alias-creator:
  image: aivero/conan:focal-x86_64
  tags: [x86_64]
  stage: init
  variables:
    GIT_DEPTH: 0
    GIT_FETCH_EXTRA_FLAGS: --depth 50
  script:
    - python3 scripts/create_aliases.py
  except:
    - master
generate-config:
  image: aivero/conan:focal-x86_64
  tags: [x86_64]
  stage: build
  script:
    - echo "CI_JOB_MANUAL ${CI_JOB_MANUAL}"
    - deno run --unstable --allow-all --import-map https://gitlab.com/aivero/open-source/cicd/-/raw/master/import_map.json https://gitlab.com/aivero/open-source/cicd/-/raw/master/lib/es6_global/src/GenerateConfig.js
  artifacts:
    paths:
      - generated-config.yml
      - build_order.json
      - lock.bundle

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config
