include:
  - project: 'aivero/cloud/cicd'
    file: 'conan-ci-base.yml'
  - project: 'aivero/cloud/cicd'
    file: 'conan-ci-amd64.yml'
variables:
  SPECIFICS: '/rust'

# https://stackoverflow.com/questions/56699829/how-to-trigger-a-specific-job-in-gitlab
pipeline_tests:
  stage: test
  image: curlimages/curl
  variables:
    SPECIFICS: ''
  extends:
    - .x86_64
  before_script: []
  script:
    - curl --request POST \
      --form token=${CI_JOB_TOKEN} \
      --form ref=master \
      --form "variables[TRIGGERED_JOB]=PIPELINE_TEST" \
      https://gitlab.com/api/v4/projects/14823826/trigger/pipeline
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
      allow_failure: false