[package]
name = "gst-realsense"
version = "0.1.0"
authors = ["Niclas Moeslund Overby <noverby@prozum.dk>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
url = "1.1"
glib = { git = "https://github.com/gtk-rs/glib" }
gstreamer = { git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", features = ["subclassing"] }
gstreamer-base = { git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", features = ["subclassing"] }
gstreamer-video = { git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
librealsense2 = "0.2.0"

[lib]
name = "gstrealsense"
crate-type = ["cdylib"]
path = "src/lib.rs"
