[package]
name = "gst-realsense"
version = "0.0.0-ohmyconanpleaseoverwriteme"
authors = ["Niclas Moeslund Overby <niclas.overby@aivero.com>", "Andrej Orsula <andrej.orsula@aivero.com>", "Tobias Morell <tobias.morell@aivero.com>"]
license = "LGPL"
description = "GStreamer plugin containing `video/rgbd` source for a RealSense device"
keywords = ["Realsense", "Source", "GStreamer", "Rust"]
repository = "https://gitlab.com/aivero/public/gstreamer/gst-realsense"
edition = "2018"
readme = "README.md"
build = "build.rs"

[dependencies]
glib = { version = "0.8" }
gstreamer = { version = "0.14", features = ["subclassing"] }
gstreamer-base = { version = "0.14", features = ["subclassing"] }
gstreamer-video = "0.14"
capnp = "0.12"
lazy_static = "1.4.0"

[dependencies.gstreamer-depth-meta]
git = "https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs"
tag = "0.3.0"

[dependencies.librealsense2]
git = "https://gitlab.com/aivero/public/librealsense-rs"
tag = "1.1.0"

[build-dependencies]
capnpc = "0.12"

[lib]
name = "gstrealsensesrc"
crate-type = ["cdylib"]
path = "src/lib.rs"
