[package]
name = "librealsense2"
version = "0.5.0"
authors = ["Niclas Moeslund Overby <noverby@prozum.dk>"]
description = "Rust bindings for librealsense2"
license = "MIT"
edition = "2018"

[dependencies]
librealsense2-sys = { git = "https://gitlab.com/aivero/streaming/librealsense-sys" }