[package]
name = "gst-rgbd"
version = "0.0.0-ohmyconanpleaseoverwriteme" # Overwritten during conan create.
authors = ["Andrej Orsula <andrej.orsula@aivero.com>", "Tobias Morell <tobias.morell@aivero.com>"]
license = "LGPL"
description = "GStreamer plugin for demuxing and muxing `video/rgbd` streams"
keywords = ["RGB-D", "Demux", "Mux", "GStreamer", "Rust"]
repository = "https://gitlab.com/aivero/public/gstreamer/gst-rgbd"
edition = "2018"
readme = "README.md"

[dependencies]
glib = "0.10"
gstreamer = "0.16"
gstreamer-base = { version = "0.16", features = ["v1_14_1"] }
lazy_static = "1.4"

[dependencies.gstreamer-depth-meta]
git = "https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs"
tag = "1.4.0"


# Run `cargo fmt -- --check` and `cargo clippy -- -D warnings` before commits
[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]

[lib]
name = "gstrgbd"
crate-type = ["cdylib"]
path = "src/lib.rs"
