[package]
name = "gst-rgbd"
version = "0.0.0-ohmyconanpleaseoverwriteme" # Overwritten during conan create.
authors = ["Andrej Orsula <andrej.orsula@aivero.com>", "Tobias Morell <tobias.morell@aivero.com>"]
license = "LGPL"
description = "GStreamer plugin for demuxing and muxing `video/rgbd` streams"
keywords = ["RGB-D", "Demux", "Mux", "GStreamer", "Rust"]
repository = "https://gitlab.com/aivero/public/gstreamer/gst-rgbd"
edition = "2018"
readme = "README.md"

[dependencies]
glib = "0.9"
gstreamer = "0.15"
gstreamer-base = { version = "0.15", features = ["dox"] }
lazy_static = "1.4"

[dependencies.gstreamer-depth-meta]
git = "https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs"
branch = "update-glib-and-gst"
# TODO: Remember to change once MR has been merged
# tag = "1.0.0"

[lib]
name = "gstrgbd"
crate-type = ["cdylib"]
path = "src/lib.rs"
