[package]
name = "gst-realsense"
version = "0.1.0"
authors = ["Niclas Moeslund Overby <noverby@prozum.dk>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
libc = "0.2"
glib = "0.7.1"
gstreamer = { version = "0.13.0", features = ["subclassing"] }
gstreamer-base = { version = "0.13.0", features = ["subclassing"] }
gstreamer-video = "0.13.0"
gstreamer-depth-meta = { git = "https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs" }
librealsense2 = "0.3.0"

[lib]
name = "gstrealsense"
crate-type = ["cdylib"]
path = "src/lib.rs"
