[package]
name = "librealsense2-sys"
version = "0.5.0"
authors = ["Niclas Moeslund Overby <noverby@prozum.dk>"]
description = "Rust FFI bindings for librealsense"
keywords = ["librealsense", "Rust", "FFI", "generated", "unsafe"]
repository = "https://gitlab.com/aivero/public/librealsense-sys"
license = "MIT"
edition = "2018"
readme = "README.md"

[build-dependencies]
pkg-config = "0.3.14"
bindgen = "0.53"
