[package]
name = "gst-realsense"
version = "0.1.0"
authors = ["Niclas Moeslund Overby <noverby@prozum.dk>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
libc = "0.2"
glib = "0.8"
gstreamer = { version = "0.14", features = ["subclassing"] }
gstreamer-base = { version = "0.14", features = ["subclassing"] }
gstreamer-video = "0.14"
gstreamer-depth-meta = { git = "https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs"}
librealsense2 = { path = "/home/andrej/work/librealsense2-rs" }

[lib]
name = "gstrealsense"
crate-type = ["cdylib"]
path = "src/lib.rs"
