[package]
name = "gstreamer-depth-meta"
version = "0.4.0"
authors = ["Niclas Moeslund Overby <noverby@prozum.dk>", "Tobias Morell <tobias.morell@aivero.com>", "Andrej Orsula <andrej.orsula@aivero.com>"]
description = "Rust bindings to gstreamer-depth-meta"
license = "Apache 2.0"
edition = "2018"

[dependencies]
glib = "0.8"
glib-sys = "0.9"
gstreamer = { version = "0.14", features = ["subclassing"] }
gstreamer-sys = "0.8"
gstreamer-video = "0.14"
gstreamer-video-sys = "0.8"
gstreamer-base = { version = "0.14", features = ["subclassing"] }
capnp = "0.12"

[build-dependencies]
pkg-config = "0.3.14"
capnpc = "0.12"

[dev-dependencies]
rand = "0.7"
