[package]
name = 'gst-k4a'
version = '0.1.0'
authors = ['Andrej Orsula <andrej.orsula@aivero.com>']
license = 'LGPL'
description = 'GStreamer plugin containing `video/rgbd` source for an Azure Kinect DK (K4A) device'
keywords = [
    'Azure Kinect',
    'K4A',
    'Source',
    'GStreamer',
    'Rust',
]
repository = 'https://gitlab.com/aivero/public/gstreamer/gst-k4a'
edition = '2018'
readme = 'README.md'

[dependencies.glib]
version = '0.8'

[dependencies.gstreamer]
version = '0.14'
features = ['subclassing']

[dependencies.gstreamer-base]
version = '0.14'
features = ['subclassing']

[dependencies.gstreamer-video]
version = '0.14'

[dependencies.gstreamer-depth-meta]
git = 'https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs'
tag = '0.2.1'

[dependencies.k4a]
git = 'https://gitlab.com/aivero/hardware/k4a-rs'
tag = '0.1.2'

[lib]
name = 'gstk4asrc'
crate-type = ['cdylib']
path = 'src/lib.rs'
