version: '3'
services:
  rgbdtoolkits:
    image: aivero-rgbd-toolkit:latest
    build:
      context: .
      args:
        - OS_VERSION=bionic
        - RGBD_TOOLKIT_VERSION=1.5.1
    restart: "never"
    volumes:
      - "$PWD./data:/root/data:rw"
    devices:
      - '/dev:/dev'
      - '/sys:/sys'
    privileged: true
    command: ["/bin/bash","entry.sh"]
