= Aivero RGB-D Toolkit

Pack of main open source GStreamer `video/rgbd` elements offered by
Aivero.

== Install

Download the tarball, then run installation as shown below.

In order to use the components, the `aivero_environment.sh` must be sourced. Only one environment
may be sourced in a single shell session, if necessary please
make sure to use multiple terminals (or terminal tabs).


== Installation

You have 4 options for installation; 
- Conan direnv
- Conan install
- docker (using conan)
- cargo (individual packages only)

Please but special cases (such as developing on sub elements) will require a conan installation.

=== Conan

You can use Aivero's artifactory instance at https://aivero.jfrog.io/ui/repos/tree/General/aivero-all[https://aivero.jfrog.io] to install the newest release straight from our CICD.

==== Conan Setup

First you need to install and setup conan, as we use that to handle our dependencies. Before you start, please make sure
that your default python version is 3.X and that pip installs packages for python 3.
We build on conan with a non-standard profile, which you can keep updated using our https://gitlab.com/aivero/open-source/conan-config[conan config]

Please install conan by running:

.Install conan and add the aivero remote
[source,bash]
----
pip install conan --user
# You may need to source ~/.profile here, please see https://docs.conan.io/en/latest/installation.html#known-installation-issues-with-pip
# Install the conan repositories, as well as conan profiles
conan config install https://gitlab.com/aivero/open-source/conan-config/-/archive/master/conan-config-master.tar.gz -sf conan-config-master

# Select one of the provided conan profiles as default:
conan config set general.default_profile=linux-x86_64

# When running on i.e. a NVIDIA TX2 or Xavier use:
# conan config set general.default_profile=linux-armv8-l4t-t186

# And to ensure that the remote is configured properly:
conan search -r aivero-all gst-rgbd-src
# You should now see a list of all the releases of our GStreamer RGB-D source elements.
----

==== Install toolkit via conan and direnv

Install direnv: https://direnv.net/ making sure to add it to your shell.

[source,bash]
----
cd aivero-rgbd-toolkit
# Generate a .envrc file that will load the correct paths into your environment
conan install . -g direnv -u
# Allow direnv to automatically load the file when entering the directory
direnv allow

# Now test if you e.g. can access realsensesrc
gst-inspect-1.0 realsensesrc
----

==== Install toolkit via conan install

Now you can locally build and install the toolkit:

.Install aivero-rgbd-toolkit using conan
[source,bash]
----
git clone https://gitlab.com/aivero/open-source/contrib.git
conan create aivero-rgbd-toolkit
# This will assemble the toolkit based on our pre-build elements on the conan server.
# It will create a conan package name based on the current git sha ref, i.e. `aivero-rgbd-toolkit/5e686b7103ac12b9a9e6c690edb0503b86005531` 
# In addition it will create a CONAN ALIAS of your current branch to the git sha based git package. You may use either to install:
# `aivero-rgbd-toolkit/master`
conan install aivero-rgbd-toolkit/master@ -if rgbd_toolkit
# This will deploy the toolkit into `./rgbd_toolkit` and configure the `aivero_environment.sh` with an absolute path. 
----

NOTE: When installing for a second time, please clear `rgbd_toolkit` first.

NOTE: If you want to move the deployment folder, please reflect the new location in the PREFIX variable inside the `aivero_environment.sh`.

=== Install as docker

The aivero-rgbd-toolkit can also be run inside a docker container. The `+docker+` subfolder contains an example `+Dockerfile+` and `+docker-compose.yml+` that can be used to build and run a container.

WARNING: You will not be able to access the X server, preventing you from showing any GUI, unless you explicitly configure both docker and your xserver. How to do this is out of scope for this readme.

NOTE: It is imperative to bind mound the `+/dev+` folder into the container and to run in `+--privileged+` mode to allow accessing the hardware. Furthermore, you still need to install the udev rules as per <<udev-rules>>.

==== Docker

[source,bash]
----
cd docker

# specify the tag or branch to use from https://gitlab.com/aivero/public/aivero-rgbd-toolkit
docker build --build-arg=OS_VERSION=bionic --build-arg=RGBD_TOOLKIT_VERSION=1.5.1 -t aivero-rgbd-toolkit .

# Enter the container and run:

docker run --rm -ti --privileged -v /dev:/dev aivero-rgbd-toolkit:latest /bin/bash
source aivero_environment.sh

# Test it, by inspecting the realsensesrc
gst-inspect-1.0 realsensesrc

----

==== docker-compose
[source,bash]
----
cd docker

# specify the tag or branch to use from https://gitlab.com/aivero/public/aivero-rgbd-toolkit inside the docker-compose.yml
docker-compose build

# Specify the command you want to run, the specified `tail -f /dev/null` does nothing and simply prevents the container from exiting
docker-compose up -d

# Test it, by inspecting the realsensesrc
docker-compose exec rgbdtoolkits /bin/bash
# inside container
source aivero_environment.sh

# Test it, by inspecting the realsensesrc
gst-inspect-1.0 realsensesrc
----

---

=== Cargo, CMAKE

You can build the rust based gstreamer elements (`realsensesrc`, `k4asrc`, `rgbdmux` and `rgbddemux` using cargo and the `colorizer` using cmake:
[source,bash]
----
git clone https://gitlab.com/aivero/open-source/contrib.git
cd gst-realsense
cargo build --release
cd ../gst-k4a
cargo build --release
cd ../gst-rgbd
carbo build --release
cd ../gst-colorizer
mkdir build && cd build
cmake .. && make -j8
----

Now just make sure they are within your `GST_PLUGIN_PATH` by appending to it, or copying the files, respectively.


---

[[udev-rules]]
=== Setup permission (udev rules)

In order to use physical RealSense or K4A devices without being 'root', you will first need to setup udev rules. For this, you can execute script(s) corresponding to your device(s):

[source,bash]
----
# RealSense
./scripts/setup_udev_rules_rs.sh
# K4A
./scripts/setup_udev_rules_k4a.sh
----

== Verify installation

After installing from either tarball or conan, you may want to verify that the installation succeeded by running:

[source,bash]
----
# adjust to point to your aivero_environment.sh file
source /opt/aivero/rgbd_toolkit/aivero_environment.sh
gst-inspect-1.0 realsensesrc
# Should show the man page for the realsensesrc
----

TIP: You will need to `source` the `aivero_environment.sh` every time you restart the terminal.

== Quick Start:

The `realsensesrc` supports two different modes of operations:

1. Playing a rosbag.
2. Playing from a physical camera.

=== Playing from rosbag

This example shows how to play from a rosbag.

Please obtain a rosbag, either by recording one with the `realsense-viewer`, or downloading
https://drive.google.com/file/d/1ZMSPY1pF9orIp473jMhwev2ObiM-jtne/view?usp=sharing[mug.bag]. These examples assume
you're using _mug.bag_.

[source, bash]
....
# Replace with the path to your rosbag
export ROSBAG=~/Downloads/mug.bag
gst-launch-1.0 realsensesrc rosbag-location=$ROSBAG real-time-rosbag-playback=true  ! \
rgbddemux name=demux \
demux.src_depth ! queue ! colorizer near-cut=300 far-cut=700 ! videoconvert ! glimagesink
....

Which will display the colorized depth data from the rosbag. Depending on the video streams present in the ROSBAG, you
may also look at infrared and colour streams:

[source, bash]
....
# Replace with the path to your rosbag
export ROSBAG=~/Downloads/mug.bag
gst-launch-1.0 realsensesrc rosbag-location=$ROSBAG real-time-rosbag-playback=true enable-infra1=true  ! \
rgbddemux name=demux \
demux.src_depth ! queue ! colorizer near-cut=300 far-cut=700 ! videoconvert ! glimagesink \
demux.src_infra1 ! queue ! videoconvert ! glimagesink
....

IMPORTANT: If you try to enable a stream which is not present in a rosbag, the `realsensesrc` will exit with an error.

=== Playing from Camera

This example shows how to play from a physical RealSense camera. The following example shows the colourised depth video
and colour video recorded by a RealSense camera:

[source, bash]
....
# Replace with the serial of your camera
export SERIAL=XXXXXXXXXXXX
gst-launch-1.0 realsensesrc serial=$SERIAL enable-color=true  ! \
rgbddemux name=demux \
demux.src_depth ! queue ! colorizer near-cut=300 far-cut=700 ! videoconvert ! glimagesink \
demux.src_color ! queue ! videoconvert ! glimagesink
....

[[gstreamer-gst-launch-10-syntax-crashcourse]]
== GStreamer gst-launch-1.0 syntax crashcourse

Besides applications and libraries that can be build with GStreamer, it
also offers a development/testing command line tool called
`gst-launch-1.0`. `gst-launch-1.0` creates a video processing pipeline based on a
simple syntax.

[source, bash]
....
source /opt/aivero/rgbd-toolkit/aivero_environment.sh
# Replace this with your ROSBAG
export ROSBAG=~/Downloads/mug.bag
GST_DEBUG=3 gst-launch-1.0 realsensesrc rosbag-location=$ROSBAG real-time-rosbag-playback=true  ! \
rgbddemux name=demux \
demux.src_depth ! queue ! colorizer near-cut=300 far-cut=700 ! videoconvert ! glimagesink
....

[start=1]

. `GST_DEBUG=3` - _Optional_. It sets the debug level of the pipeline, where `3` means errors, warnings and fixmes.
Setting a higher value will flood your console with output, so we recommend filtering the output if you need higher values,
as such: `GST_DEBUG=3,realsensesrc:6`.

. `gst-launch-1.0` - The start of a every command.

. `realsensesrc rosbag-location=$ROSBAG real-time-rosbag-playback=true` - A source element with
three of its parameters specified. You can access the man page of an element using i.e. `gst-inspect-1.0 realsensesrc`.
The different timestamp modes and playback modes are explained below.

. `!` - The exclamation mark (padded by space left and right) links
two elements together, so that data can flow between them. This link
will only succeed if both elements support each others capabilities
(`caps`). `realsensesrc` has (simplified) caps: `video/rgbd` and
so has `rgbddemux`

. `rgbddemux name=demux` - The demuxing element that takes caps
`video/rgbd` and spits out elementary streams. We have also overridden
it's a unique name with our own *unique* name (this can be done on every
element)

. ` ` - Note the *lack* of an exclamation mark (`!`) after `rgbddemux name=demux`. We do
not link this element at this point further.

. `demux.src_depth` - This is a reference to a src pad of the
`rgbddemux`. For every stream that the `rgbddemux` finds upstream it
will create a src pad that produces data. We can access the pad by a dot
followed by the pad name (`.src_*name_of_stream*`, where `*name_of_stream*` could be `color`, `depth`, etc.). The caps
of the video stream on that pad in the case of uncompressed depth video are `video/x-raw,format=GRAY16_LE`, i.e. 16-bit
Little Endian gray-scale video.

== Troubleshooting

Check out the issues for

* https://gitlab.com/aivero/open-source/contrib/-/issues[Aivero Contrib issue tracker]

=== Missing a rust installation

If you are compiling you need to install rust. You may do this via the usual rust channels.

