# #######
# Build and test the Release version:
# #######

armv8-bionic-release-stable-tx1:
  extends: armv8-bionic-release-stable
  variables:
    CONAN_BUILD_OPTIONS: "-s hardware.board=t210"
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"

armv8-bionic-release-testing-tx1:
  extends: armv8-bionic-release-testing
  variables:
    CONAN_BUILD_OPTIONS: "-s hardware.board=t210"
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"

# #######
# Build and test the Debug version:
# #######

armv8-bionic-debug-stable-tx1:
  extends: armv8-bionic-debug-stable
  variables:
    CONAN_BUILD_OPTIONS: "-s hardware.board=t210"
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"

armv8-bionic-debug-testing-tx1:
  extends: armv8-bionic-debug-testing
  variables:
    CONAN_BUILD_OPTIONS: "-s hardware.board=t210"
    CONAN_SKIP_BROKEN_SYMLINKS_CHECK: "True"
