version: 2
updates:
  - directory: "/gst-depth-meta-rs"
    package-ecosystem: "cargo"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
  - directory: "/rgbd-enums"
    package-ecosystem: "cargo"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"