name: Alias remover
on:
  delete: ~
  workflow_dispatch: ~
jobs:
  remover:
    name: '${{ github.event.ref_type }}: ${{ github.event.ref }}'
    container:
      image: aivero/conan:bionic-x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        submodules: true
    - uses: aivero/actions/runner@master
      with:
        cmds: '["python3 contrib/scripts/remove_aliases.py"]'
      env:
        GIT_REF: ${{ github.event.ref }}
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_LOGIN_PASSWORD: ${{ secrets.CONAN_LOGIN_PASSWORD }}
        CONAN_CONFIG_URL: ${{ secrets.CONAN_CONFIG_URL }}
        CONAN_CONFIG_DIR: ${{ secrets.CONAN_CONFIG_DIR }}
        CONAN_REPO_ALL: ${{ secrets.CONAN_REPO_ALL }}
        CONAN_REPO_REMOVE: ${{ secrets.CONAN_REPO_INTERNAL }}
