name: Alias creator
on:
  create
jobs:
  creator:
    name: '${{ github.event.ref_type }}: ${{ github.event.ref }}'
    runs-on: x64
    container:
      image: aivero/conan:bionic-x86_64
    steps:
    - uses: aivero/checkout@main
      with:
        ref: ${{ github.event.ref }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - name: Create and upload aliases
      uses: aivero/runner-action@test
      with:
        cmds: '["python3 scripts/upload_aliases.py"]'
      env:
        GIT_REF: ${{ github.event.ref }}
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_LOGIN_PASSWORD: ${{ secrets.CONAN_LOGIN_PASSWORD }}
        CONAN_CONFIG_URL: ${{ secrets.CONAN_CONFIG_URL }}
        CONAN_CONFIG_DIR: ${{ secrets.CONAN_CONFIG_DIR }}
        CONAN_REPO_ALL: ${{ secrets.CONAN_REPO_ALL }}
        CONAN_REPO_UPLOAD: ${{ secrets.CONAN_REPO_PUBLIC }}
