name: Alias creator
on:
  create: ~
  workflow_dispatch: ~
jobs:
  creator:
    name: '${{ github.event.ref_type }}: ${{ github.event.ref }}'
    container:
      image: aivero/conan:bionic-x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - name: Create and upload aliases
      uses: aivero/actions/runner@master
      with:
        cmds: '["python3 scripts/upload_aliases.py"]'
      env:
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_LOGIN_PASSWORD: ${{ secrets.CONAN_LOGIN_PASSWORD }}
        CONAN_CONFIG_URL: ${{ secrets.CONAN_CONFIG_URL }}
        CONAN_CONFIG_DIR: ${{ secrets.CONAN_CONFIG_DIR }}
        CONAN_REPO_ALL: ${{ secrets.CONAN_REPO_ALL }}
        CONAN_REPO_UPLOAD: ${{ secrets.CONAN_REPO_PUBLIC }}
