name: Alias remover
on:
  delete
jobs:
  remover:
    name: 'Remove aliases: ${{ github.ref }}'
    runs-on: x64
    container:
      image: aivero/conan:bionic-x86_64
    steps:
    - uses: aivero/checkout@main
      with:
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - name: Create and upload aliases
      uses: aivero/runner-action@test
      with:
        cmds: '["python3 scripts/remove_aliases.py"]'
      env:
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_LOGIN_PASSWORD: ${{ secrets.CONAN_LOGIN_PASSWORD }}
        CONAN_CONFIG_URL: ${{ secrets.CONAN_CONFIG_URL }}
        CONAN_CONFIG_DIR: ${{ secrets.CONAN_CONFIG_DIR }}
        CONAN_REPO_ALL: ${{ secrets.CONAN_REPO_ALL }}
        CONAN_REPO_REMOVE: ${{ secrets.CONAN_REPO_PUBLIC }}
