name: Conan Build and Upload
on:
  repository_dispatch:
    types: [conan]
jobs:
  build:
    runs-on: ${{ github.event.client_payload.tags }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: Install apt dependencies
      run: sudo apt install python3-setuptools
    - name: Install pip dependencies
      run: python3 -m pip install --upgrade pip conan
    - name: Conan Create
      uses: aivero/conan-action@test
      with:
        package: ${{ github.event.client_payload.package }}
        profile: ${{ github.event.client_payload.profile }}
        path: ${{ github.event.client_payload.path }}
        conan_config: ${{ github.event.client_payload.conan_config }}
        conan_repo: ${{ github.event.client_payload.conan_repo }}