name: Conan Create and Upload
on:
  repository_dispatch:
    types: [conan]
jobs:
  build:
    name: ${{ github.event.client_payload.package }} - ${{ github.event.client_payload.profile }}
    runs-on: ${{ github.event.client_payload.tags }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - name: Install apt dependencies
      run: sudo apt install python3-setuptools
    - name: Install pip dependencies
      run: python3 -m pip install --upgrade pip conan
    - name: Conan Create
      uses: aivero/conan-action@test
      with:
        package: ${{ github.event.client_payload.package }}
        profile: ${{ github.event.client_payload.profile }}
        path: ${{ github.event.client_payload.path }}
        conan_repo: ${{ github.event.client_payload.conan_repo }}
      env:
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_LOGIN_PASSWORD: ${{ secrets.CONAN_LOGIN_PASSWORD }}
        CONAN_CONFIG_URL: ${{ secrets.CONAN_CONFIG_URL }}
        CONAN_CONFIG_DIR: ${{ secrets.CONAN_CONFIG_DIR }}
