name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image_name: [bionic-x86_64-bootstrap,bionic-x86_64,bionic-armv8-bootstrap,bionic-armv8,dispatch]
    steps:
      - uses: actions/checkout@v2

      - name: Install qemu-user-static
        run: sudo apt update && sudo apt install qemu-user-static
        if: ${{ contains(matrix.image_name, 'armv8') }}

      - name: Run tests
        run: docker build . --file ${{ matrix.image_name }}.Dockerfile

  push:
    needs: test

    runs-on: ubuntu-20.04
    if: github.event_name == 'push'

    strategy:
      matrix:
        image_name: [bionic-x86_64-bootstrap,bionic-x86_64,bionic-armv8-bootstrap,bionic-armv8,dispatch]

    steps:
      - uses: actions/checkout@v2

      - name: Install qemu-user-static
        run: sudo apt update && sudo apt install qemu-user-static
        if: ${{ contains(matrix.image_name, 'armv8') }}

      - name: Build image
        run: docker build . --file ${{ matrix.image_name }}.Dockerfile --tag aivero/conan:${{ matrix.image_name }}

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_CONAN_TOKEN }}" | docker login --username aivero --password-stdin

      - name: Push image
        run: docker push aivero/conan:${{ matrix.image_name }}
